Add health endpoint to Node-RED server
IBM/node-red-app pull request #25
Opened 2020-09-16 19:35 UTC by youming-lin

Add health check endpoint to server, always

2020-09-16 22:11 UTC, knolleary commented
This is the right general approach for solving the question of adding the `/health` endpoint, but you don't need to copy in the whole of the code quite like this. A lot of it is handling command-line arguments - which is completely irrelevant for the starter kit. It can be trimmed back considerably.

2020-09-16 22:22 UTC, youming-lin commented
@knolleary I agree. My take on a proper solution would be to essentially take that code and rewrite it into just the bits and pieces we need (may also refactor index.js as well), though admittedly I'm not familiar with the code.

We also talked about having the node-red lib set up the health check endpoint itself, though I was personally against it. Do you think this is the better solution?

2020-09-16 22:31 UTC, knolleary commented
Where is this discussion happening? As the originator of the Node-RED starter kit, I'd like to be in the loop on discussions that affect it.

The code exists the way it does because it was the most efficient way to bootstrap a node-red app with a custom getting-started set of screens. I'm not adversed to it being refactored, but there needs to be a clear purpose for doing that refactoring - a clear problem to solve.

I suggest starting by stripping out all the command-line parsing logic in `red.js` within this PR. I can then help refine it further.

2020-09-16 23:25 UTC, youming-lin commented
Just within the team right now. I hit this issue, did this quick implementation, brought it up to team, they offered a different idea (I @'ed you in the internal GHE issue on our board).

I'm for improving this PR, as I don't think adding health check to node-red lib adds much value to other users of the lib, and it creates an implicit dependency between the lib and the DevOps toolchain template (toolchain deployment failing health check stage is why I'm adding the health endpoint; there are other solutions besides this but felt this was the right solution). It's also faster to make the change here since the node-red lib probably has its own lengthy process to release a new version.

As for the refactoring, it didn't make much sense to me to keep the red.js file as a script as we are not consuming it via CLI, might as well turn it into an exportable module and/or include in index.js itself.

2020-09-17 17:58 UTC, youming-lin commented
@knolleary I've made more changes. Can you review again?

2020-09-23 08:02 UTC, knolleary requested changes
Looks good - just one more bit to remove then its :+1: from me.

2020-09-23 15:19 UTC, youming-lin commented on red.js
> +  }
I've removed the code block.

2020-09-23 15:19 UTC, youming-lin commented
@knolleary I have removed that `if` block now. Can you review again?

2020-09-25 07:50 UTC, knolleary approved these changes

2020-09-25 15:09 UTC, merged